allmunis={
    #municipal districts
    "Acadia": "#Acadia",
    "Athabasca": "#Athabasca",
    "Barrhead": "#Barrhead",
    "Beaver": "#Beaver",
    "Big Lakes": "#BigLakes",
    "Bighorn": "#Bighorn",
    "Birch Hills": "#BirchHills",
    "Bonnyville": "#Bonnyville",
    "Brazeau":"#Brazeau",
    "Camrose": "#Camrose",
    "Cardson": "#Cardston",
    "Clear Hills": "#ClearHills",
    "Clearwater": "#Clearwater",
    "Cypress": "#Cypress",
    "Fairview": "#Fairview",
    "Flagstaff": "#Flagstaff",
    "Foothills": "#Foothills",
    "Forty Mile": "#FortyMile",
    "Grand Prarie": "#GrandPrarie",
    "Greenview": "#Flagstaff",
    "Kneehill": "#Kneehill",
    "Lac Ste. Anne": "#LacSteAnne",
    "Lacombe": "#Lacombe",
    "Lamont": "#Lamont",
    "Leduc": "#Leduc",
    "Lesser Slave River": "#LesserSlaveRiver",
    "Lethbridge": "#Lethbridge",
    "Minburn": "#Minburn",
    "Mountain View": "#MountainView",
    "Newell": "#Newell",
    "Northern Lights": "#NorthernLights",
    "Northern Sunrise": "#NorthernSunrise",
    "Oppurtunity": "#Oppurtunity",
    "Paintearth": "#Paintearth",
    "Parkland": "#Parkland",
    "Peace": "#Peace",
    "Pincher Creek": "#PincherCreek",
    "Ponoka": "#Ponoka",
    "Provost": "#Provost",
    "Ranchland": "#Ranchland",
    "Red Deer": "#RedDeer",
    "Rocky View": "#RockyView",
    "Saddle Hills": "#SaddleHills",
    "Smoky Lake": "#SmokyLake",
    "Smoky River": "#SmokyRiver",
    "Spirit River": "#SpiritRiver",
    "St. Paul": "#StPaul",
    "Starland": "#Starland",
    "Stettler": "#Stettler",
    "Sturgeon": "#Sturgeon",
    "Taber": "#Taber",
    "Thorhild": "#Thorhild",
    "Two Hills": "#TwoHills",
    "Vermilion River": "#VermilionRiver",
    "Vulcan": "#Vulcan",
    "Wainwright": "#Wainwright",
    "Warner": "#Warner",
    "Westlock": "#Westlock",
    "Wetaskiwin": "#Wetaskiwin",
    "Wheatland": "#Wheatland",
    "Willow Creek": "#WillowCreek",
    "Woodlands": "#Woodlands",
    "Yellowhead": "#Yellowhead",
    #Improvement District
    "Waterton": "#Waterton",
    "Jasper": "#Jasper",
    "Kananaskis": "#Kananaskis",
    "Banff": "#Banff",
    "Elk Island": "#ElkIsland",
    "Willmore": "#Willmore",
    #Cities
    "Airdrie": "#Airdrie",
    "Beaumont": "#Beaumont",
    "Brooks": "#Brooks",
    "Calgary": "#Calgary",
    "Camrose": "#Camrose",
    "Chestermere": "#Chestermere",
    "Cold Lake": "#ColdLake",
    "Edmonton": "#Edmonton",
    "Fort Saskatchewan": "#FortSaskatchewan",
    "Grande Prarie": "#GrandePrarie",
    "Lacombe": "#Lacombe",
    "Leduc": "#Leduc",
    "Lethbridge": "#Lethbridge",
    "Lloydminster": "#Lloydminster",
    "Medicine Hat": "#MedicineHat",
    "Red Deer": "#RedDeer",
    "Spruce Grove": "#SpruceGrove",
    "St. Albert": "#StAlbert",
    "Wetaskiwin": "#Wetaskiwin",
    #Specialized Municipalities
    "Crowsnest Pass": "#CrowsnestPass",
    "Jasper": "#Jasper",
    "Lac La Biche": "#LacLaBiche",
    "Mackenzie": "#Mackenzie",
    "Strathcona": "#Strathcona",
    "Wood Buffalo": "#WoodBuffalo",
    #Towns
    "Athabasca": "#Athabasca",
    "Banff": "#Banff",
    "Barrhead": "#Barrhead",
    "Bashaw": "#Bashaw",
    "Bassano": "#Bassano",
    "Beaverlodge": "#Beaverlodge",
    "Bentley": "#Bentley",
    "Black Diamond": "#BlackDiamond",
    "Blackfalds": "#Blackfalds",
    "Bonnyville": "#Bonnyville",
    "Bowden": "#Bowden",
    "Calmar": "#Calmar",
    "Cardston": "#Cardston",
    "Castor": "#Castor",
    "Coaldale": "#Coaldale",
    "Cochrane": "#Cochrane",
    "Crossfield": "#Crossfield",
    "Devon": "#Devon",
    "Drayton Valley": "#DraytonValley",
    "Eckville": "#Eckville",
    "Elk Point": "#ElkPoint",
    "Falher": "#Falher",
    "Fox Creek": "#FoxCreek",
    "Grimshaw": "#Grimshaw",
    "Hardisty": "#Hardisty",
    "High Prarie": "#HighPrarie",
    "Hinton": "#Hinton",
    "Irricana": "#Irricana",
    "Lamont": "#Lamont",
    "Magrath": "#Magrath",
    "Mayerthorpe": "#Mayerthorpe",
    "Milk River": "#MilkRiver",
    "Morinville": "#Morinville",
    "Nanton": "#Nanton",
    "Okotoks": "#Okotoks",
    "Onoway": "#Onoway",
    "Peace River": "#PeaceRiver",
    "Picture Butte": "#PictureButte",
    "Ponoka": "#Ponoka",
    "Rainbow Lake": "#RainbowLake",
    "Redcliff": "#Redcliff",
    "Rimbey": "#Rimbey",
    "Sedgewick": "#Sedgewick",
    "Slave Lake": "#SlaveLake",
    "Spirit River": "#SpiritRiver",
    "Stavely": "#Stavely",
    "Stony Plain": "#StonyPlain",
    "Sundre": "#Sundre",
    "Sylvan Lake": "#SylvanLake",
    "Thorsby": "#Thorsby",
    "Tofield": "#Tofield",
    "Turner Valley": "#TurnerValley",
    "Valleyview": "#Valleyview",
    "Vegreville": "#Vegreville",
    "Wainwright": "#Wainwright",
    "Viking": "#Viking",
    "Westlock": "#Westlock",
    "Bon Accord": "#BonAccord",
    "Bow Island": "#BowIsland",
    "Bruderheim": "#Bruderheim",
    "Canmore": "#Canmore",
    "Carstairs": "#Carstairs",
    "Claresholm": "#Claresholm",
    "Coalhurst": "#Coalhurst",
    "Coronation": "#Coronation",
    "Daysland": "#Daysland",
    "Didsbury": "#Didsbury",
    "Drumheller": "#Drumheller",
    "Edson": "#Edson",
    "Fairview": "#Fairview",
    "Fort Macleod": "#FortMacleod",
    "Gibbons": "#Gibbons",
    "Hanna": "#Hanna",
    "High Level": "#HighLevel",
    "High River": "#HighRiver",
    "Killam": "#Killam",
    "Innisfail": "#Innisfail",
    "Legal": "#Legal",
    "Manning": "#Manning",
    "McLennan": "#McLennan",
    "Millet": "#Millet",
    "Nobleford": "#Nobleford",
    "Mundare": "#Mundare",
    "Olds": "#Olds",
    "Oyen": "#Oyen",
    "Penhold": "#Penhold",
    "Pincher Creek": "#PincherCreek",
    "Provost": "#Provost",
    "Raymond": "#Raymond",
    "Redwater": "#Redwater",
    "Rocky Mountain House": "#RockyMountainHouse",
    "Sexsmith": "#Sexsmith",
    "Smoky Lake": "#SmokyLake",
    "St. Paul": "#StPaul",
    "Stettler": "#Stettler",
    "Strathmore": "#Strathmore",
    "Swan Hills": "#SwanHills",
    "Taber": "#Taber",
    "Three Hills": "#ThreeHills",
    "Trochu": "#Trochu",
    "Two Hills": "#TwoHills",
    "Vauxhall": "#Vauxhall",
    "Vermilion": "#Vermilion",
    "Vulcan": "#Vulcan",
    "Wembley": "#Wembley",


    


}

